name: autocomplete
channels:
  - conda-forge
  - defaults
dependencies:
  - poetry=1.8.1
  - pip=24.0
  - python=3.11.8
  - wheel=0.42.0
  - bokeh=3.2.2
  - pandas=1.5.3
  - panel=1.3.8
  - pyyaml=6.0.1
  - pyarrow=15.0.0
